debug: false

spring:
  application:
    name: spring-boot-redis
  profiles:
    active: prod

---
# dev
spring:
  profiles:
    dev
  redis:
    host: 10.26.21.3
    port: 6385
    database: 0

---
# prod
spring:
  profiles:
    prod
  redis:
    host: m11466.zeus.redis.ljnode.com
    port: 11466
    database: 0

